# Generated by Django 3.0 on 2021-02-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.CharField(choices=[('', 'Seleccione horario'), ('23 de febrero', '23 de febrero'), ('24 de febrero', '24 de febrero')], max_length=15)),
                ('hour', models.CharField(choices=[('', 'Seleccione horario'), ('9-10', '9-10'), ('10-11', '10-11'), ('11-12', '11-12'), ('12-13', '12-13'), ('14-15', '14-15'), ('15-16', '15-16'), ('16-17', '16-17'), ('17-18', '17-18'), ('18-19', '18-19')], default=None, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address_V', models.GenericIPAddressField(null=True)),
                ('visit_day', models.DateTimeField(auto_now_add=True)),
                ('location_country', models.CharField(db_index=True, max_length=30)),
                ('location_city', models.CharField(db_index=True, max_length=30)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('browser_type', models.CharField(blank=True, max_length=50)),
                ('browser_version', models.CharField(db_index=True, max_length=64)),
                ('os_type', models.CharField(blank=True, max_length=50)),
                ('os_version', models.CharField(db_index=True, max_length=64)),
            ],
        ),
    ]
